language: python
python:
  - "2.7"
  - "3.3"
#  - "3.2"

# command to install dependencies
install:
  - pip install -e ".[test,dev,werkzeug]"

# command to run tests
script:
  - nosetests --with-coverage --cover-package=appmetrics --cover-erase

after_success:
  # code coverage
  - coveralls
